### ISSUE TITLE
Is there a way to check if the conection is up?

### ISSUE THREAD

**Issue by eduardrock** [tryggingamidstodin/node-jt400#42]
I need to know if there is a method to check if the connection to DB2 is active.

**Comment by bergur** [comment]
Hi @eduardrock 

I can't check right now, but you can try `pool.isClosed()` or `pool.getAvailableConnectionCount()`

Otherwise I'll look beter into this tomorrow :)

**Comment by eduardrock** [comment]
@bergur  I've checked those two methods but they don't exist.

**Comment by eduardrock** [comment]
The problem I got is that the DB2 database I'm connecting is inside a VPN, but sometimes that VPN fails and get disconnected for some minutes, so then when it comes back again, the connection to DB2 with node-jt400 doesn't respond, it get stuck.

**Comment by cwg999** [comment]
"the connection to DB2 doesn't respond and gets stuck" 
So... for example, the next pool.query command you do never responds? Maybe it would suffice to somehow set a timeout instead of checking if the connection exists? I think mine cleanly errors out when I get disconnected, but I'll have to check.

**Comment by coinnect-project** [comment]
i have similar problem. it seems that if my nodejs web service stays idle for a few hours, the pool closes the connection and i have this state:

> ago 06 15:18:16 localhost.localdomain node[20194]: mar ago 6 15:18:16:488 CEST 2019  as400: ConnectionPool com.ibm.as400.access.AS400JDBCConnectionPool@6cc9c0a9 (1825161385) : com.ibm.as400.access.AS400JDBCPooledConnection@48f3b15f.
ago 06 15:18:16 localhost.localdomain node[20194]: mar ago 6 15:18:16:488 CEST 2019  as400: ConnectionPool com.ibm.as400.access.AS400JDBCConnectionPool@6cc9c0a9 (1825161385) : Removing expired connection from the pool..
ago 06 15:18:16 localhost.localdomain node[20194]: mar ago 6 15:18:16:488 CEST 2019  as400: ConnectionPool com.ibm.as400.access.AS400JDBCConnectionPool@6cc9c0a9 (1825161385) : com.ibm.as400.access.AS400JDBCPooledConnection@48f3b15f.
ago 06 15:18:16 localhost.localdomain node[20194]: mar ago 6 15:18:16:488 CEST 2019  as400: ConnectionPool com.ibm.as400.access.AS400JDBCConnectionPool@6cc9c0a9 (1825161385) : Removing dead connection from the pool..
ago 06 15:18:16 localhost.localdomain node[20194]: mar ago 6 15:18:16:504 CEST 2019  as400: Connection S2120CEW (1223930207)  closed.
ago 06 15:18:16 localhost.localdomain node[20194]: mar ago 6 15:18:16:504 CEST 2019  as400: PooledConnection com.ibm.as400.access.AS400JDBCPooledConnection@48f3b15f (1223930207) : close() was called on this AS400JDBCPooledConnection.
ago 06 15:18:16 localhost.localdomain node[20194]: mar ago 6 15:18:16:504 CEST 2019  as400: ConnectionPool com.ibm.as400.access.AS400JDBCConnectionPool@6cc9c0a9 (1825161385) : ConnectionPool cleanup finished..
ago 06 15:18:16 localhost.localdomain node[20194]: mar ago 6 15:18:16:504 CEST 2019  as400: ConnectionPool com.ibm.as400.access.AS400JDBCConnectionPool@6cc9c0a9 (1825161385) :    Idle Connections: 0.
ago 06 15:18:16 localhost.localdomain node[20194]: mar ago 6 15:18:16:504 CEST 2019  as400: ConnectionPool com.ibm.as400.access.AS400JDBCConnectionPool@6cc9c0a9 (1825161385) :    Active Connections: 0.
ago 06 15:18:16 localhost.localdomain node[20194]: mar ago 6 15:18:16:504 CEST 2019  as400: ConnectionPool com.ibm.as400.access.AS400JDBCConnectionPool@6cc9c0a9 (1825161385) :    Dead Connections: 0.



then, if i try to execute another request, i see that the pool try to reopen another connection but then i get a connectiondropped exception..

> ago 07 16:50:22 localhost.localdomain node[20194]: mer ago 7 16:50:22:676 CEST 2019  as400: ConnectionPool com.ibm.as400.access.AS400JDBCConnectionPool@6cc9c0a9 (1825161385) : Filling the pool with 1 connections..
ago 07 16:50:22 localhost.localdomain node[20194]: mer ago 7 16:50:22:782 CEST 2019  as400: Toolbox for Java - Open Source Software, JTOpen 9.1, codebase 5770-SS1 V7R3M0.00 built=20160705 @RF
ago 07 16:50:22 localhost.localdomain node[20194]: mer ago 7 16:50:22:782 CEST 2019  as400: JDBC Level: 40
ago 07 16:50:22 localhost.localdomain node[20194]: mer ago 7 16:50:22:785 CEST 2019  as400@setString: Properties  (1225358173) : package ccsid = "1144".
ago 07 16:50:22 localhost.localdomain node[20194]: mer ago 7 16:50:22:785 CEST 2019  as400: Connection 192.168.10.250 (999295049) : Client CCSID = 1144.
ago 07 16:50:22 localhost.localdomain node[20194]: mer ago 7 16:50:22:785 CEST 2019  as400: Connection 192.168.10.250 (999295049) : Setting server NLV = 2932.
ago 07 16:50:22 localhost.localdomain node[20194]: mer ago 7 16:50:22:785 CEST 2019  as400: Connection 192.168.10.250 (999295049) : Client functional level = V7R2M01   .
ago 07 16:50:22 localhost.localdomain node[20194]: mer ago 7 16:50:22:785 CEST 2019  as400: Connection 192.168.10.250 (999295049) : Data compression = RLE.
ago 07 16:50:22 localhost.localdomain node[20194]: mer ago 7 16:50:22:785 CEST 2019  as400: Connection 192.168.10.250 (999295049) : ROWID supported = true.
ago 07 16:50:22 localhost.localdomain node[20194]: mer ago 7 16:50:22:785 CEST 2019  as400: Connection 192.168.10.250 (999295049) : True auto-commit supported = true.
ago 07 16:50:22 localhost.localdomain node[20194]: mer ago 7 16:50:22:785 CEST 2019  as400: Connection 192.168.10.250 (999295049) : 128 byte column names supported = true.
ago 07 16:50:22 localhost.localdomain node[20194]: mer ago 7 16:50:22:786 CEST 2019  as400: Connection 192.168.10.250 (999295049) : 128 length schema names supported = true.
ago 07 16:50:22 localhost.localdomain node[20194]: mer ago 7 16:50:22:786 CEST 2019  as400: Connection 192.168.10.250 (999295049) : Maximum decimal precision = 31.
ago 07 16:50:22 localhost.localdomain node[20194]: mer ago 7 16:50:22:786 CEST 2019  as400: Connection 192.168.10.250 (999295049) : Maximum decimal scale = 31.
ago 07 16:50:22 localhost.localdomain node[20194]: mer ago 7 16:50:22:786 CEST 2019  as400: Connection 192.168.10.250 (999295049) : Minimum divide scale = 0.
ago 07 16:50:22 localhost.localdomain node[20194]: mer ago 7 16:50:22:786 CEST 2019  as400: Connection 192.168.10.250 (999295049) : Translate hex = character.
ago 07 16:50:22 localhost.localdomain node[20194]: mer ago 7 16:50:22:786 CEST 2019  as400: Connection 192.168.10.250 (999295049) : query optimize goal = 0.
ago 07 16:50:22 localhost.localdomain node[20194]: mer ago 7 16:50:22:786 CEST 2019  as400: Connection 192.168.10.250 (999295049) : query storage limit = -1.
ago 07 16:50:22 localhost.localdomain node[20194]: mer ago 7 16:50:22:786 CEST 2019  as400: Connection 192.168.10.250 (999295049) : Using extended datastreams.
ago 07 16:50:22 localhost.localdomain node[20194]: mer ago 7 16:50:22:875 CEST 2019  as400: Connection 192.168.10.250 (999295049) : JDBC driver major version = 11.
ago 07 16:50:22 localhost.localdomain node[20194]: mer ago 7 16:50:22:876 CEST 2019  as400: Connection 192.168.10.250 (999295049) : IBM i VRM = V7R2M0.
ago 07 16:50:22 localhost.localdomain node[20194]: mer ago 7 16:50:22:876 CEST 2019  as400: Connection 192.168.10.250 (999295049) : Server CCSID = 1144.
ago 07 16:50:22 localhost.localdomain node[20194]: mer ago 7 16:50:22:876 CEST 2019  as400: Connection 192.168.10.250 (999295049) : Server functional level = V7R2M00016 (16).
ago 07 16:50:22 localhost.localdomain node[20194]: mer ago 7 16:50:22:876 CEST 2019  as400: Connection 192.168.10.250 (999295049) : Server job identifier = 646486/QUSER/QZDASOINIT.
ago 07 16:50:22 localhost.localdomain node[20194]: mer ago 7 16:50:22:876 CEST 2019  as400: Connection S2120CEW (999295049)  open.
ago 07 16:50:22 localhost.localdomain node[20194]: mer ago 7 16:50:22:876 CEST 2019  as400@setProperties: Connection S2120CEW (999295049) : Auto commit = "true".
ago 07 16:50:22 localhost.localdomain node[20194]: mer ago 7 16:50:22:877 CEST 2019  as400@setProperties: Connection S2120CEW (999295049) : Read only = "false".
ago 07 16:50:22 localhost.localdomain node[20194]: mer ago 7 16:50:22:877 CEST 2019  as400@setProperties: Connection S2120CEW (999295049) : Transaction isolation = "1".
ago 07 16:50:22 localhost.localdomain node[20194]: mer ago 7 16:50:22:877 CEST 2019  as400: ConnectionPoolDataSource  (1203189789) : connection created.
ago 07 16:50:22 localhost.localdomain node[20194]: mer ago 7 16:50:22:877 CEST 2019  as400: Statement STMT0001 (2123530591)  open. Parent: Connection S2120CEW (999295049) .
ago 07 16:50:22 localhost.localdomain node[20194]: mer ago 7 16:50:22:877 CEST 2019  as400@AS400JDBCStatement.init: Statement STMT0001 (2123530591) : Escape processing = "true".
ago 07 16:50:22 localhost.localdomain node[20194]: mer ago 7 16:50:22:877 CEST 2019  as400@AS400JDBCStatement.init: Statement STMT0001 (2123530591) : Fetch direction = "1000".
ago 07 16:50:22 localhost.localdomain node[20194]: mer ago 7 16:50:22:877 CEST 2019  as400@AS400JDBCStatement.init: Statement STMT0001 (2123530591) : Fetch size = "0".
ago 07 16:50:22 localhost.localdomain node[20194]: mer ago 7 16:50:22:877 CEST 2019  as400@AS400JDBCStatement.init: Statement STMT0001 (2123530591) : Max field size = "0".
ago 07 16:50:22 localhost.localdomain node[20194]: mer ago 7 16:50:22:877 CEST 2019  as400@AS400JDBCStatement.init: Statement STMT0001 (2123530591) : Max rows = "0".
ago 07 16:50:22 localhost.localdomain node[20194]: mer ago 7 16:50:22:877 CEST 2019  as400@AS400JDBCStatement.init: Statement STMT0001 (2123530591) : Query timeout = "0".
ago 07 16:50:22 localhost.localdomain node[20194]: mer ago 7 16:50:22:878 CEST 2019  as400@AS400JDBCStatement.init: Statement STMT0001 (2123530591) : Result set concurrency = "1007".
ago 07 16:50:22 localhost.localdomain node[20194]: mer ago 7 16:50:22:878 CEST 2019  as400@AS400JDBCStatement.init: Statement STMT0001 (2123530591) : Result set holdability = "1".
ago 07 16:50:22 localhost.localdomain node[20194]: mer ago 7 16:50:22:878 CEST 2019  as400@AS400JDBCStatement.init: Statement STMT0001 (2123530591) : Result set type = "1003".
ago 07 16:50:22 localhost.localdomain node[20194]: mer ago 7 16:50:22:878 CEST 2019  as400@AS400JDBCStatement.init: Statement STMT0001 (2123530591) : Behavior Override = "0".
ago 07 16:50:22 localhost.localdomain node[20194]: mer ago 7 16:50:22:878 CEST 2019  as400: Statement STMT0001 (2123530591) : Data to correlate statement with cursor Cursor CRSR0001 (202462239) .
ago 07 16:50:22 localhost.localdomain node[20194]: mer ago 7 16:50:22:879 CEST 2019  as400: Statement STMT0001 (2123530591) : Executing query, SQL Statement -->[SELECT CURRENT SCHEMA FROM SYSIBM/SYSDUMMY1].
ago 07 16:50:23 localhost.localdomain node[20194]: mer ago 7 16:50:23:145 CEST 2019  as400: Statement STMT0001 (2123530591) : Prepared STMT0001*, SQL Statement -->[SELECT CURRENT SCHEMA FROM SYSIBM/SYSDUMMY1].
ago 07 16:50:23 localhost.localdomain node[20194]: mer ago 7 16:50:23:293 CEST 2019  as400: Cursor CRSR0001 (202462239)  open.
ago 07 16:50:23 localhost.localdomain node[20194]: mer ago 7 16:50:23:294 CEST 2019  as400: Cursor CRSR0001 (202462239)  closed.
ago 07 16:50:23 localhost.localdomain node[20194]: mer ago 7 16:50:23:294 CEST 2019  as400: Statement STMT0001 (2123530591) : getBlockingFactor(): Blocking -- blockCriteria_=2 and isForFetchOnly.
ago 07 16:50:23 localhost.localdomain node[20194]: mer ago 7 16:50:23:294 CEST 2019  as400: Statement STMT0001 (2123530591) : getBlockingFactor: blockFactor is 252.
ago 07 16:50:23 localhost.localdomain node[20194]: mer ago 7 16:50:23:294 CEST 2019  as400: ResultSet CRSR0001 (1336285778)  open. Parent: Statement STMT0001 (2123530591) .
ago 07 16:50:23 localhost.localdomain node[20194]: mer ago 7 16:50:23:295 CEST 2019  as400@AS400JDBCResultSet: ResultSet CRSR0001 (1336285778) : Conncurrency = "1007".
ago 07 16:50:23 localhost.localdomain node[20194]: mer ago 7 16:50:23:295 CEST 2019  as400@AS400JDBCResultSet: ResultSet CRSR0001 (1336285778) : Fetch direction = "1000".
ago 07 16:50:23 localhost.localdomain node[20194]: mer ago 7 16:50:23:295 CEST 2019  as400@AS400JDBCResultSet: ResultSet CRSR0001 (1336285778) : Fetch size = "0".
ago 07 16:50:23 localhost.localdomain node[20194]: mer ago 7 16:50:23:295 CEST 2019  as400@AS400JDBCResultSet: ResultSet CRSR0001 (1336285778) : Max rows = "0".
ago 07 16:50:23 localhost.localdomain node[20194]: mer ago 7 16:50:23:295 CEST 2019  as400@AS400JDBCResultSet: ResultSet CRSR0001 (1336285778) : Type = "1003".
ago 07 16:50:23 localhost.localdomain node[20194]: mer ago 7 16:50:23:295 CEST 2019  as400: Statement STMT0001 (2123530591) : Executed STMT0001*, SQL Statement --> [SELECT CURRENT SCHEMA FROM SYSIBM/SYSDUMMY1].
ago 07 16:50:23 localhost.localdomain node[20194]: mer ago 7 16:50:23:295 CEST 2019  as400: Statement STMT0001 (2123530591) : Update count = -1.
ago 07 16:50:23 localhost.localdomain node[20194]: mer ago 7 16:50:23:296 CEST 2019  as400: Statement STMT0001 (2123530591) : Result set = true.
ago 07 16:50:23 localhost.localdomain node[20194]: mer ago 7 16:50:23:296 CEST 2019  as400: Statement STMT0001 (2123530591) : Number of result sets = 0.
ago 07 16:50:23 localhost.localdomain node[20194]: mer ago 7 16:50:23:296 CEST 2019  as400: Statement STMT0001 (2123530591) : Row count estimate = 1.
ago 07 16:50:23 localhost.localdomain node[20194]: mer ago 7 16:50:23:296 CEST 2019  as400: ResultSet CRSR0001 (1336285778)  closed.
ago 07 16:50:23 localhost.localdomain node[20194]: mer ago 7 16:50:23:306 CEST 2019  as400: Statement STMT0001 (2123530591)  closed.
ago 07 16:50:23 localhost.localdomain node[20194]: mer ago 7 16:50:23:307 CEST 2019  as400: PooledConnection com.ibm.as400.access.AS400JDBCPooledConnection@3b900849 (999295049) : A new AS400JDBCPooledConnection was created.
ago 07 16:50:23 localhost.localdomain node[20194]: mer ago 7 16:50:23:307 CEST 2019  as400: ConnectionPoolDataSource  (1203189789) : PooledConnection created.
ago 07 16:50:23 localhost.localdomain node[20194]: mer ago 7 16:50:23:307 CEST 2019  as400: PooledConnection com.ibm.as400.access.AS400JDBCPooledConnection@3b900849 (999295049) : AS400JDBCPooledConnection.getConnection() was called.
ago 07 16:50:23 localhost.localdomain node[20194]: mer ago 7 16:50:23:307 CEST 2019  as400: ConnectionHandle S2120CEW (1959760303) : Warning: returning pooled connection's AS400 object directly to user..
ago 07 16:50:26 localhost.localdomain node[20194]: mer ago 7 16:50:26:677 CEST 2019  as400: PooledConnection com.ibm.as400.access.AS400JDBCPooledConnection@3b900849 (999295049) : This AS400JDBCPooledConnection is being returned..
ago 07 16:50:26 localhost.localdomain node[20194]: mer ago 7 16:50:26:678 CEST 2019  as400@setAutoCommit: Connection S2120CEW (999295049) : Auto commit = "true".
ago 07 16:50:26 localhost.localdomain node[20194]: mer ago 7 16:50:26:678 CEST 2019  as400@setTransactionIsolation: Connection S2120CEW (999295049) : Transaction isolation = "1".
ago 07 16:50:26 localhost.localdomain node[20194]: mer ago 7 16:50:26:679 CEST 2019  as400@setHoldability: Connection S2120CEW (999295049) : Holdability = "1".
ago 07 16:50:26 localhost.localdomain node[20194]: mer ago 7 16:50:26:679 CEST 2019  as400: PreparedStatement STMT0001 (452166668)  open. Parent: Connection S2120CEW (999295049) .
ago 07 16:50:26 localhost.localdomain node[20194]: mer ago 7 16:50:26:679 CEST 2019  as400@AS400JDBCStatement.init: PreparedStatement STMT0001 (452166668) : Escape processing = "true".
ago 07 16:50:26 localhost.localdomain node[20194]: mer ago 7 16:50:26:679 CEST 2019  as400@AS400JDBCStatement.init: PreparedStatement STMT0001 (452166668) : Fetch direction = "1000".
ago 07 16:50:26 localhost.localdomain node[20194]: mer ago 7 16:50:26:679 CEST 2019  as400@AS400JDBCStatement.init: PreparedStatement STMT0001 (452166668) : Fetch size = "0".
ago 07 16:50:26 localhost.localdomain node[20194]: mer ago 7 16:50:26:679 CEST 2019  as400@AS400JDBCStatement.init: PreparedStatement STMT0001 (452166668) : Max field size = "0".
ago 07 16:50:26 localhost.localdomain node[20194]: mer ago 7 16:50:26:680 CEST 2019  as400@AS400JDBCStatement.init: PreparedStatement STMT0001 (452166668) : Max rows = "0".
ago 07 16:50:26 localhost.localdomain node[20194]: mer ago 7 16:50:26:680 CEST 2019  as400@AS400JDBCStatement.init: PreparedStatement STMT0001 (452166668) : Query timeout = "0".
ago 07 16:50:26 localhost.localdomain node[20194]: mer ago 7 16:50:26:680 CEST 2019  as400@AS400JDBCStatement.init: PreparedStatement STMT0001 (452166668) : Result set concurrency = "1007".
ago 07 16:50:26 localhost.localdomain node[20194]: mer ago 7 16:50:26:680 CEST 2019  as400@AS400JDBCStatement.init: PreparedStatement STMT0001 (452166668) : Result set holdability = "1".
ago 07 16:50:26 localhost.localdomain node[20194]: mer ago 7 16:50:26:680 CEST 2019  as400@AS400JDBCStatement.init: PreparedStatement STMT0001 (452166668) : Result set type = "1003".
ago 07 16:50:26 localhost.localdomain node[20194]: mer ago 7 16:50:26:680 CEST 2019  as400@AS400JDBCStatement.init: PreparedStatement STMT0001 (452166668) : Behavior Override = "0".
ago 07 16:50:26 localhost.localdomain node[20194]: mer ago 7 16:50:26:680 CEST 2019  as400: PreparedStatement STMT0001 (452166668) : Data to correlate statement with cursor Cursor CRSR0001 (1370611446) .
ago 07 16:50:26 localhost.localdomain node[20194]: mer ago 7 16:50:26:680 CEST 2019  as400: PreparedStatement STMT0001 (452166668) : isjvm16Synchronizer=false.
ago 07 16:50:26 localhost.localdomain node[20194]: mer ago 7 16:50:26:681 CEST 2019  as400: PreparedStatement STMT0001 (452166668) : Preparing [SET CURRENT SCHEMA DEFAULT].
ago 07 16:50:26 localhost.localdomain node[20194]: mer ago 7 16:50:26:690 CEST 2019  as400: PreparedStatement STMT0001 (452166668) : Prepared STMT0001*, SQL Statement -->[SET CURRENT SCHEMA DEFAULT].
ago 07 16:50:26 localhost.localdomain node[20194]: mer ago 7 16:50:26:691 CEST 2019  as400: PreparedStatement STMT0001 (452166668) : Executed STMT0001*, SQL Statement --> [SET CURRENT SCHEMA DEFAULT].
ago 07 16:50:26 localhost.localdomain node[20194]: mer ago 7 16:50:26:691 CEST 2019  as400: PreparedStatement STMT0001 (452166668) : Update count = 0.
ago 07 16:50:26 localhost.localdomain node[20194]: mer ago 7 16:50:26:691 CEST 2019  as400: PreparedStatement STMT0001 (452166668) : Result set = false.
ago 07 16:50:26 localhost.localdomain node[20194]: mer ago 7 16:50:26:691 CEST 2019  as400: PreparedStatement STMT0001 (452166668) : Number of result sets = 0.
ago 07 16:50:26 localhost.localdomain node[20194]: mer ago 7 16:50:26:691 CEST 2019  as400: PreparedStatement STMT0001 (452166668) : Row count estimate = -1.
ago 07 16:50:26 localhost.localdomain node[20194]: mer ago 7 16:50:26:697 CEST 2019  as400: PreparedStatement STMT0001 (452166668)  closed.
ago 07 16:50:26 localhost.localdomain node[20194]: mer ago 7 16:50:26:697 CEST 2019  as400: Unknown com.ibm.as400.access.PoolConnectionEventListener@4b3a3085 (1262104709) : Returning active connection to the pool..
ago 07 16:50:26 localhost.localdomain node[20194]: error catch program
ago 07 16:50:26 localhost.localdomain node[20194]: { [Error: Error running instance method
ago 07 16:50:26 localhost.localdomain node[20194]: com.ibm.as400.access.ConnectionDroppedException: Connection was dropped unexpectedly.
ago 07 16:50:26 localhost.localdomain node[20194]: at com.ibm.as400.access.ClientAccessDataStream.construct(ClientAccessDataStream.java:62)
ago 07 16:50:26 localhost.localdomain node[20194]: at com.ibm.as400.access.AS400ThreadedServer.run(AS400ThreadedServer.java:357)
ago 07 16:50:26 localhost.localdomain node[20194]: at java.lang.Thread.run(Thread.java:748)
ago 07 16:50:26 localhost.localdomain node[20194]: ]
ago 07 16:50:26 localhost.localdomain node[20194]: cause: nodeJava_com_ibm_as400_access_ConnectionDroppedException {} }

why connection doesn't wake up correctly? i saw also this parameters in logs:

>  MaxLifeTime: 86400000.
  MaxUseTime: -1.
MaxInactivity: 3600000.
  PretestConnections: false.

can be a solution to set them without a timeout so the connection never closes? how can i set this in case it is possible?

**Comment by bergur** [comment]
Hi, sorry for the late reply.

I will try to add this over the weekend.

**Comment by eduardrock** [comment]
@bergur 
Is there any updates? It's almost one year since I opened this issue and still can't get any solution for this problem.

**Comment by cwg999** [comment]
At this rate it might be better for you to try to attempt it yourself. Download open jt400 and add it to your class path and then connect using the AS400

https://www.ibm.com/support/knowledgecenter/ssw_ibm_i_72/rzahh/javadoc/com/ibm/as400/access/AS400.html?view=embed

All classes (for i 7.2) jt400:
https://www.ibm.com/support/knowledgecenter/ssw_ibm_i_72/rzahh/javadoc/allclasses-noframe.html?view=embed

Then see how this project uses the npm module "java" to wrap java functions into node. 
Then try seeing if you can leverage one of the java commands to achieve adding whether or not the connection exists, or maybe listen to the event.

**Comment by bergur** [comment]
Hi @eduardrock 

I understand your frustration. Its hard for us to support feature requests since my 9 to 5 job is programming what the management of TM (icelandic insurance company) wants us to develop.

This module is just a byproduct of that since at one time we needed to connect to AS400.

We try to answer every message we get but we don't have any real good time to write feature requests or go over pull requests. We do try, but there is alot of waiting. My aplogize for that.

If I find any freetime during the weekend I might be able to take a look at this but as Cody mentioned your best bet is probably to make a pull request...then the waiting time is only 2-4 weeks instead of a year (facepalm).

I am really sorry for the delay and I understand that this affects your project and work.

**Comment by sorensenNiels** [comment]
Sorry if this one does not fully solve your problem - I have on the other hand used the approach of performing the following query in order to verify that the connection is up and running.
const result = await pool.query('values current date');
if all is good you will get the current date back if not it fails and you now the connection is down, and you can recycle the connection.
@bergur  If you need help with node-jt400 let me know - my main knowledge is around IBM i - Java (JT400) and node js (Typescript) - I will start out looking at the issues reported.

**Comment by bergur** [comment]
HJi @sorensenNiels 

Thanks for your offer, that sounds really good.

Regarding checking the connection, if you have a java code that uses isConnected or isConnectionAlive to check the connection then I could implement it in this module somewhat quickly.

**Comment by sorensenNiels** [comment]
Hi @bergur Will do! Have been looking at the code and found that I would love to run the provided test cases - of course I could start providing the required IBM i objects but on the other hand maybe you have a savefile with the required objects :-) Can you provide? I have additional questions on the use of Java 6 and the promise package of Q.

**Comment by sorensenNiels** [comment]
Hi @bergur - we both have our day job and wondering if you had the SQL script for tsttbl - I'm running tests at the moment for isConnected and additional features for the IFS (get list of fields/folders in folder) finally I will be doing a PR for you.

**Comment by bergur** [comment]
Hi @sorensenNiels 

I've added to sql to the test folder, check out a790234

**Comment by Mattperkinsee** [comment]
It seems like you could program this on your end @edu791 by handling the errors from the connection and the queries. If the query fails then attempt to reconnect. If the reconnect fails then you know it can't be reached for whatever reason. Then code something to retry the connection until it succeeds. 

I use PM2 as sort of a workaround for this. If the program crashes or errors out then it restarts the program. You can configure the restart options in PM2 to however you wish (add delays, max attempts, etc...)
