### ISSUE TITLE
java.sql.SQLException: Cursor state not valid.

### ISSUE THREAD

**Issue by woodinteractive** [tryggingamidstodin/node-jt400#44]
My content is successfully writing to the DB, but I'm getting a error response anyway and I'm not sure it the issue is with my implementation or what. Any insights would be appreciated.

My code:
```javascript 
pool.query(`INSERT INTO ${User.table} (${keys}) VALUES (${values})`)
  .then(result => {
    response.sendStatus(201).json({
      code: 201,
      message: 'User created.',
    })
  })
  .catch(error => {
    console.log(error)
  })
```

Query:
```SQL
INSERT INTO DWOOD.QCUSTCDT (CUSNUM,LSTNAM,INIT,STREET,CITY,STATE,ZIPCOD,CDTLMT,CHGCOD,BALDUE,CDTDUE) VALUES (123456,'Wood','D J','9401 Kellogg','Wchita','KS',67207,2000,2,123.09,0) params: []
```

Error log:
```INSERT INTO DWOOD.QCUSTCDT (CUSNUM,LSTNAM,INIT,STREET,CITY,STATE,ZIPCOD,CDTLMT,CHGCOD,BALDUE,CDTDUE) VALUES (123456,'Wood','D J','9401 Kellogg','Wchita','KS',67207,2000,2,123.09,0) params: []
{ [Error: Error running instance method
java.sql.SQLException: Cursor state not valid.
        at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:857)
        at com.ibm.as400.access.JDError.throwSQLException(JDError.java:412)
        at com.ibm.as400.access.AS400JDBCPreparedStatement.executeQuery(AS400JDBCPreparedStatement.java:1766)
        at nodejt400.JdbcJsonClient.query(Unknown Source)
        at nodejt400.JT400.query(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
] cause: nodeJava_java_sql_SQLException {} }
```

**Comment by cwg999** [comment]
1. With insert statements I use
```
baseConnection.update(sql, values);
```
2.  At the end of the SQL I use `WITH NONE` for tables without journaling.

**Comment by woodinteractive** [comment]
I figured it out. I was using a static method on a class to execute the call and it wasn't returning correct. Nothing wrong with your package.

**Comment by bergur** [comment]
@woodinteractive

Thanks for the update. Glad it all worked out
