### ISSUE TITLE
Delete on empty table wrong error message

### ISSUE THREAD

**Issue by samuelexyz** [tryggingamidstodin/node-jt400#51]
Hi , 
When i run a delete on an empty table i got this error message:

 name: 'ProgrammerError',
  category: 'ProgrammerError',
  context: { sql: 'delete from persons', params: [] },
  cause:
   { Error: Error running instance method
   java.sql.SQLException: Cursor state not valid.
        at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:857)
        at com.ibm.as400.access.JDError.throwSQLException(JDError.java:412)
        at com.ibm.as400.access.AS400JDBCPreparedStatement.executeQuery(AS400JDBCPreparedStatement.java:1766)
        at nodejt400.JdbcJsonClient.query(Unknown Source)

But is a SQL100 no record found for delete message, is this an issue?

There is a way to get the sql message and the sql id code of the error.

Thank you
S.

**Comment by cwg999** [comment]
The error is thrown `e`:
`e.message` returns `"[SQL0204] PERSONS in *LIBL type *FILE not found."`

so as a quick hack you could
`e.message.slice(1,e.message.search(/\]/))` which returns `SQL0204`

**Comment by samuelexyz** [comment]
@cwg999 where did you see the message, table exists and library list is specified.
I activate the trace :

ven gen 3 07:59:52:077 CET 2020  as400: PreparedStatement STMT0001 (1383011625) : Executed STMT0001*, SQL Statement --> [delete from persons WITH NC].
ven gen 3 07:59:52:077 CET 2020  as400: PreparedStatement STMT0001 (1383011625) : Update count = 0.
ven gen 3 07:59:52:077 CET 2020  as400: PreparedStatement STMT0001 (1383011625) : Result set = false.
ven gen 3 07:59:52:077 CET 2020  as400: PreparedStatement STMT0001 (1383011625) : Number of result sets = 0.
ven gen 3 07:59:52:077 CET 2020  as400: PreparedStatement STMT0001 (1383011625) : Row count estimate = -1.
ven gen 3 07:59:52:078 CET 2020  Class com.ibm.as400.access.AS400JDBCDriver was loaded from file:/Users/samuelerenati/Documents/ProgettiNode/knex/node_modules/node-jt400/java/lib/jt400.jar!/com/ibm/as400/access/AS400JDBCDriver.class
ven gen 3 07:59:52:082 CET 2020  as400: PreparedStatement STMT0001 (1383011625) : Throwing exception, sqlState: 24000 reason: Cursor state not valid. vendor code -99999.java.sql.SQLException: Cursor state not valid.
        at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:857)
        at com.ibm.as400.access.JDError.throwSQLException(JDError.java:412)
        at com.ibm.as400.access.AS400JDBCPreparedStatement.executeQuery(AS400JDBCPreparedStatement.java:1766)
        at nodejt400.JdbcJsonClient.query(Unknown Source)
        at nodejt400.JT400.query(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)

ven gen 3 07:59:52:105 CET 2020  as400: PreparedStatement STMT0001 (1383011625)  closed.
ven gen 3 07:59:52:105 CET 2020  as400: PooledConnection com.ibm.as400.access.AS400JDBCPooledConnection@5348cc0d (1397279757) : This AS400JDBCPooledConnection is being returned..
ven gen 3 07:59:52:179 CET 2020  as400@setAutoCommit: Connection ASPRIVP2 (1397279757) : Auto commit = "true".
ven gen 3 07:59:52:180 CET 2020  as400: PreparedStatement STMT0001 (880108507)  open. Parent: Connection ASPRIVP2 (1397279757) .
ven gen 3 07:59:52:180 CET 2020  as400@AS400JDBCStatement.init: PreparedStatement STMT0001 (880108507) : Escape processing = "true".
ven gen 3 07:59:52:180 CET 2020  as400@AS400JDBCStatement.init: PreparedStatement STMT0001 (880108507) : Fetch direction = "1000".
ven gen 3 07:59:52:180 CET 2020  as400@AS400JDBCStatement.init: PreparedStatement STMT0001 (880108507) : Fetch size = "0".
ven gen 3 07:59:52:180 CET 2020  as400@AS400JDBCStatement.init: PreparedStatement STMT0001 (880108507) : Max field size = "0".
ven gen 3 07:59:52:180 CET 2020  as400@AS400JDBCStatement.init: PreparedStatement STMT0001 (880108507) : Max rows = "0".
ven gen 3 07:59:52:181 CET 2020  as400@AS400JDBCStatement.init: PreparedStatement STMT0001 (880108507) : Query timeout = "0".
ven gen 3 07:59:52:181 CET 2020  as400@AS400JDBCStatement.init: PreparedStatement STMT0001 (880108507) : Result set concurrency = "1007".
ven gen 3 07:59:52:181 CET 2020  as400@AS400JDBCStatement.init: PreparedStatement STMT0001 (880108507) : Result set holdability = "1".
ven gen 3 07:59:52:181 CET 2020  as400@AS400JDBCStatement.init: PreparedStatement STMT0001 (880108507) : Result set type = "1003".
ven gen 3 07:59:52:181 CET 2020  as400@AS400JDBCStatement.init: PreparedStatement STMT0001 (880108507) : Behavior Override = "0".
ven gen 3 07:59:52:181 CET 2020  as400: PreparedStatement STMT0001 (880108507) : Data to correlate statement with cursor Cursor CRSR0001 (86420992) .
ven gen 3 07:59:52:181 CET 2020  as400: PreparedStatement STMT0001 (880108507) : isjvm16Synchronizer=false.
ven gen 3 07:59:52:181 CET 2020  as400: PreparedStatement STMT0001 (880108507) : Preparing [SET CURRENT SCHEMA DEFAULT].
ven gen 3 07:59:52:224 CET 2020  as400: PreparedStatement STMT0001 (880108507) : Prepared STMT0001*, SQL Statement -->[SET CURRENT SCHEMA DEFAULT].
ven gen 3 07:59:52:251 CET 2020  as400: PreparedStatement STMT0001 (880108507) : Executed STMT0001*, SQL Statement --> [SET CURRENT SCHEMA DEFAULT].
ven gen 3 07:59:52:251 CET 2020  as400: PreparedStatement STMT0001 (880108507) : Update count = 0.
ven gen 3 07:59:52:251 CET 2020  as400: PreparedStatement STMT0001 (880108507) : Result set = false.
ven gen 3 07:59:52:251 CET 2020  as400: PreparedStatement STMT0001 (880108507) : Number of result sets = 0.
ven gen 3 07:59:52:251 CET 2020  as400: PreparedStatement STMT0001 (880108507) : Row count estimate = -1.
ven gen 3 07:59:52:274 CET 2020  as400: PreparedStatement STMT0001 (880108507)  closed.
ven gen 3 07:59:52:275 CET 2020  as400: Unknown com.ibm.as400.access.PoolConnectionEventListener@1f5a9653 (526030419) : Returning active connection to the pool.

But if i see the error message i have no error code:

 { Error: Error running instance method
   java.sql.SQLException: Cursor state not valid.
        at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:857)
        at com.ibm.as400.access.JDError.throwSQLException(JDError.java:412)
        at com.ibm.as400.access.AS400JDBCPreparedStatement.executeQuery(AS400JDBCPreparedStatement.java:1766)
        at nodejt400.JdbcJsonClient.query(Unknown Source)
        at nodejt400.JT400.query(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
    cause: nodeJava_java_sql_SQLException {} },
  id: '5aac399a-fe4a-443c-9707-e812314c7121' }
we got programmer error
category ProgrammerError
message Cursor state not valid.
original error { [Error: Error running instance method
java.sql.SQLException: Cursor state not valid.
        at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:857)
        at com.ibm.as400.access.JDError.throwSQLException(JDError.java:412)
        at com.ibm.as400.access.AS400JDBCPreparedStatement.executeQuery(AS400JDBCPreparedStatement.java:1766)
        at nodejt400.JdbcJsonClient.query(Unknown Source)
        at nodejt400.JT400.query(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
] cause: nodeJava_java_sql_SQLException {} }

**Comment by cwg999** [comment]
my basic code was 

```
pool.query(`DELETE FROM PERSONS`)
  .then((results) => {console.log(results)})
  .catch((e) =>{ console.log(e)})
```

**Comment by samuelexyz** [comment]
@cwg999 according to docs delete require update method 

pool
  .update('DELETE FROM PERSONS')
  .then(nUpdated => {
    console.log('Deleted + ' nUpdated + ' rows');
});

I think you get not found because you don't have PERSONS file in your library list

**Comment by cwg999** [comment]
Hi Sam. In your code please add a `.catch(e => console.log(e.message))` and let me know the output.

**Comment by samuelexyz** [comment]
@cwg999 as i wrote message are "Cursor state not valid"

console.log('category', e.category); 
console.log('message', e.message); 
console.log('original error', e.cause);

**category** ProgrammerError
**message** Cursor state not valid.
**original error** { [Error: Error running instance method
java.sql.SQLException: Cursor state not valid.
at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:857)
at com.ibm.as400.access.JDError.throwSQLException(JDError.java:412)
at com.ibm.as400.access.AS400JDBCPreparedStatement.executeQuery(AS400JDBCPreparedStatement.java:1766)
at nodejt400.JdbcJsonClient.query(Unknown Source)
at nodejt400.JT400.query(Unknown Source)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
] cause: nodeJava_java_sql_SQLException {} }

**Comment by cwg999** [comment]
Ahh.  I understand now. So the code is calling .next() inappropriately, or the SQL state should be returned after every request such that you can detect an SQL100 which means "no data".

**Comment by cwg999** [comment]
When I run this on an empty table I do not get this error, 
`mainPool.update('DELETE FROM FOOBAR');`

**Comment by samuelexyz** [comment]
@cwg999 you must resolve the promise otherwise you don't get the error

mainPool.update('DELETE FROM FOOBAR')
.then(nUpdated => {
console.log('Deleted + ' nUpdated + ' rows');
}).
catch( err => {
    console.dir(err);
});

**Comment by cwg999** [comment]
Yes I understand, my `update` promise resolves to an empty array with no errors.

**Comment by cwg999** [comment]
I created a new table with two columns, inserted a row, deleted the rows, then called the function again on the empty table and didn't have any errors. I got a new connection each time I did this, however.

**Comment by samuelexyz** [comment]
@cwg999 sorry found error thanks

**Comment by cwg999** [comment]
Ha! What was it?

**Comment by samuelexyz** [comment]
my fault, there was a wrong condition and i'm calling query method instead update
