### ISSUE TITLE
Error: libjvm.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by woodinteractive** [tryggingamidstodin/node-jt400#55]
I'm currently using your package with a nestjs application. When I compile the application and run it using standard `node main.js` command...everything works just fine. However, if I use a node process manager [PM2](https://pm2.keymetrics.io/) it get the following error. Not sure if you have any advice on what I can check/do to resolve this? Any help is appreciated.

```
Error: libjvm.so: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:807:18)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at Module.Hook._require.Module.require (/home/dwood/.nvm/versions/node/v10.16.3/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:80:39)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/mnt/document-root/sites/node.vtoll.ksturnpike.com/node_modules/java/lib/nodeJavaBridge.js:21:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)```

**Comment by bergur** [comment]
Hi @woodinteractive 

Looks like a problem with java. Does PM2 have java home folder?

You can look at some issues here about making sure the java module, that this module depends on, is working.

E.g make a small program with the java module, make sure that node javatest.js is working and then pm2

**Comment by woodinteractive** [comment]
I think it's now resolve. Here's what I did.

1. Update my node version to 12.16.3
2. Deleted my `node_modules` director and reinstalled using `npm install`
3. Then ran an update on PM2

And that seemed to do the trick.
