### ISSUE TITLE
BLOB insert problem

### ISSUE THREAD

**Issue by coinnect-project** [tryggingamidstodin/node-jt400#64]
Hi,
I need to write into a table which represents file attachments; this table has a BLOB column where I have to write the file itself.
Note that I used to write in the table with pure java code without any problem. Now I need to write from nodejs, using multer as utility to receive files from the web.
I tried to do the query in this ways (as explained in docs):
`pool
  .update('INSERT INTO table (id,  attachment) VALUES(?, ?)', [1,  {type:'BLOB',value: new Uint8Array(req.files.attachments[0].buffer)}])`
or
`pool
  .update('INSERT INTO table (id,  attachment) VALUES(?, ?)', [1,  {type:'BLOB',value: Uint8Array.from(req.files.attachments[0].buffer)}])`

but I get this error
`cause: [Error: Error running instance method
  java.lang.ClassCastException: org.json.simple.JSONObject cannot be cast to java.lang.String
        at nodejt400.JdbcJsonClient.setParams(Unknown Source)
        at nodejt400.JdbcJsonClient.update(Unknown Source)
        at nodejt400.JT400.update(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
  ] {
    cause: nodeJava_java_lang_ClassCastException {}
  },`

So it seems that json in params array is not recognized in the library....
I also tried this:

`pool
  .update('INSERT INTO table (id,  attachment) VALUES(?, ?)', [1,  {type:'BLOB', value: Uint8Array.from(req.files.attachments[0].buffer).toString()}])`

but I get

`cause: [Error: Error running instance method
  java.sql.SQLException: The number of parameter values set or registered does not match the number of parameters.
        at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:828)
        at com.ibm.as400.access.JDError.throwSQLException(JDError.java:412)
        at com.ibm.as400.access.AS400JDBCPreparedStatement.commonExecuteBefore(AS400JDBCPreparedStatement.java:766)
        at com.ibm.as400.access.AS400JDBCStatement.commonExecute(AS400JDBCStatement.java:943)
        at com.ibm.as400.access.AS400JDBCPreparedStatement.executeUpdate(AS400JDBCPreparedStatement.java:1829)
        at nodejt400.JdbcJsonClient.update(Unknown Source)
        at nodejt400.JT400.update(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
  ] {
    cause: nodeJava_java_sql_SQLException {}
  },`

So what is the correct way to write the blob starting from a buffer representing a file? 

I very need this 
thanks

**Comment by cwg999** [comment]
This is the test code for CLOB 
```
  it('should insert clob', async () => {
    const largeText = readFileSync(
      __dirname + '/../../test-data/clob.txt'
    ).toString()
    await connection.update('update tsttbl set clob=?', [
      { type: 'CLOB', value: largeText }
    ])
    const res: any = await connection.query('SELECT clob from tsttbl')
    expect(res[0].CLOB.length).to.equal(largeText.length)
  })
  ```

Maybe to get around your issue for now you want to just insert the record without the BLOB and then try updating it like above. In the first error it appears it doesn't like your buffer being passed, and in the second it appears that the custom "types" aren't being transformed when it's passed as an array.

**Comment by bergur** [comment]
Hi @coinnect-project

The value needs to be a string. 

The first error is the module not being able to convert correctly to params since you're passing an array:
`{ type: 'BLOB', value: [0,0,0] }`

and value needs to be a string

The second error is telling you that the parameter count doesn't match since the the array becomes comma seperated values.

`{ type: 'BLOB': value 0,0,0 }`

You should be able to do something like:

`pool .update('INSERT INTO table (id, attachment) VALUES(?, ?)', [1, {type:'BLOB',value: Buffer.from(req.files.attachments[0].buffer).toString()}])`

**Comment by coinnect-project** [comment]
> Hi @coinnect-project
> 
> The value needs to be a string.
> 
> The first error is the module not being able to convert correctly to params since you're passing an array:
> `{ type: 'BLOB', value: [0,0,0] }`
> 
> The second error is telling you that the parameter count doesn't match since the the array becomes comma seperated values.
> 
> `{ type: 'BLOB': value 0,0,0 }`
> 
> You should be able to do something like:
> 
> `pool .update('INSERT INTO table (id, attachment) VALUES(?, ?)', [1, {type:'BLOB',value: Buffer.from(req.files.attachments[0].buffer).toString()}])`
> 
> The string can be anything, a buffer, binary, long documents, etc. We're using this to store xml from a soap web service.

Hi,
it's not working...result is the same of second try:
` java.sql.SQLException: The number of parameter values set or registered does not match the number of parameters.`

I also tried to insert without blob then update only that column but I get the same error...

**Comment by bergur** [comment]
Hi @coinnect-project 

I see your problem now, you're saying `type: BLOB`, its` type: CLOB`

:)

**Comment by coinnect-project** [comment]
> Hi @coinnect-project
> 
> I see your problem now, you're saying `type: BLOB`, its` type: CLOB` - Character Large Object, which can hold 2 gb.
> https://www.ibm.com/docs/en/db2-for-zos/12?topic=columns-large-object-data-types
> 
> And yes we are using this in production and have been since we added this to the module. We are using this to insert large XML responses from a SOAP Webservice to our database.

if I use CLOB 

`[id_as,{type:'CLOB', value: Buffer.from(req.files.attachments[0].buffer).toString()}]`

I get this

` fullStack: [Function],
  category: 'ProgrammerError',
  context: {
    sql: 'INSERT INTO ERNWRK.CWEVA00F(EAIDREP,EAATTACH) VALUES(?,?)',
    params: [ 254570, [Object] ]
  },
  cause: [Error: Error running instance method
  java.sql.SQLException: Data type mismatch. (class java.lang.NumberFormatException)
        at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:828)
        at com.ibm.as400.access.JDError.throwSQLException(JDError.java:553)
        at com.ibm.as400.access.SQLBlobLocator.set(SQLBlobLocator.java:272)
        at com.ibm.as400.access.AS400JDBCPreparedStatement.setCharacterStream(AS400JDBCPreparedStatement.java:2638)
        at com.ibm.as400.access.AS400JDBCPreparedStatement.setClob(AS400JDBCPreparedStatement.java:3849)
        at nodejt400.JdbcJsonClient.setParams(Unknown Source)
        at nodejt400.JdbcJsonClient.update(Unknown Source)
        at nodejt400.JT400.update(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
  Caused by: java.lang.NumberFormatException
        at com.ibm.as400.access.BinaryConverter.stringToBytes(BinaryConverter.java:625)
        at com.ibm.as400.access.BinaryConverter.stringToBytes(BinaryConverter.java:576)
        at com.ibm.as400.access.BinaryConverter.stringToBytes(BinaryConverter.java:569)
        at com.ibm.as400.access.SQLBlobLocator.set(SQLBlobLocator.java:267)
        ... 9 more
  ] {
    cause: nodeJava_java_sql_SQLException {}`

as400 column is defined as blob

**Comment by bergur** [comment]
Yeah that makes sense. We're using java JT40400's functions behind the scene, so when type is Clob we call the function setClob which then returns data type mismatch from a blob field.

Clob is Character Large Object, which is used when varchar or other text fields are too small. 
Blob is Binary Large Object, which is used for large non-character data.

I should be able to add blob data type to this module rather quickly since it's just copy paste from clob. Just a matter of spare time.

**Comment by coinnect-project** [comment]
> Yeah that makes sense. We're using java JT40400's functions behind the scene, so when type is Clob we call the function setClob which then returns data type mismatch from a blob field.
> 
> Clob is Character Large Object, which is used when varchar or other text fields are too small.
> Blob is Binary Large Object, which is used for large non-character data.
> 
> I should be able to add blob data type to this module rather quickly since it's just copy paste from clob. Just a matter of spare time.

Yes we insert pdf and image files so column must be a blob...

I'll wait thanks 😉

**Comment by bergur** [comment]
...and just to avoid confusion or misunderstanding, you _can_ store pdf and images in a clob field. It just takes up more space since you will need to store the string value of it (e.g. base64)

**Comment by coinnect-project** [comment]
Hi,
imaging you had no time to look into this tried to do myself. 
I created a pull request, don't know if is the best way to do it but for me is working fine.

**Comment by coinnect-project** [comment]
hello? 😅

**Comment by OlafurTorfi** [comment]
Hi @coinnect-project 

I have reviewed your pull request. It is looking great. Thanks a lot. I'll be happy to merge it, once the semver version has been updated.
