### ISSUE TITLE
can not install package

### ISSUE THREAD

**Issue by gudsok** [tryggingamidstodin/node-jt400#84]
Hi ,

I have an issue when I try npm i  node-jt400 on CentOS v7.9.2009 , npm version 8.19.2 and  i get this error 

npm ERR! code 1
npm ERR! path /home/me/api-source/namecode/node_modules/java
npm ERR! command failed
npm ERR! command sh -c -- node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.1.0
npm ERR! gyp info using node@16.18.1 | linux | x64
npm ERR! gyp info find Python using Python version 3.6.8 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/me/api-source/namecode/node_modules/java/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/me/.cache/node-gyp/16.18.1/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/me/.cache/node-gyp/16.18.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/me/.cache/node-gyp/16.18.1/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/me/api-source/namecode/node_modules/java',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! node:internal/errors:478
npm ERR!     ErrorCaptureStackTrace(err);
npm ERR!     ^
npm ERR! 
npm ERR! TypeError [ERR_STREAM_NULL_VALUES]: May not write null values to stream
npm ERR!     at new NodeError (node:internal/errors:387:5)
npm ERR!     at _write (node:internal/streams/writable:301:11)
npm ERR!     at Socket.Writable.write (node:internal/streams/writable:336:10)
npm ERR!     at /home/me/api-source/namecode/node_modules/java/findJavaHome.js:6:18
npm ERR!     at /home/me/api-source/namecode/node_modules/find-java-home/dist/index.js:103:21
npm ERR!     at step (/home/me/api-source/namecode/node_modules/find-java-home/dist/index.js:46:23)
npm ERR!     at Object.next (/home/me/api-source/namecode/node_modules/find-java-home/dist/index.js:27:53)
npm ERR!     at fulfilled (/home/met/api-source/namecode/node_modules/find-java-home/dist/index.js:18:58) {
npm ERR!   code: 'ERR_STREAM_NULL_VALUES'
npm ERR! }
npm ERR! gyp: Call to 'node findJavaHome.js' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:284:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
npm ERR! gyp ERR! System Linux 3.10.0-1160.99.1.el7.x86_64
npm ERR! gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /home/me/api-source/namecode/node_modules/java
npm ERR! gyp ERR! node -v v16.18.1
npm ERR! gyp ERR! node-gyp -v v9.1.0
npm ERR! gyp ERR! not ok

how should I do to fix it

**Comment by gudsok** [comment]
I found a solution. i command  npm i  in node_module folder and it works.
